language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower gulp'
  - 'npm install' # install npm packages
  - 'bower install --no-interactive --production' # install bower packages without asking about version conflict and install last version
after_script:
  - 'gulp test' # run test
  - 'gulp codacy' # send codacy coverage
