node_js:
  - '0.10.33'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install bower karma gulp jshint karma-jasmine jasmine-core karma-chrome-launcher karma-coverage'
  - 'npm install' # install npm packages
  - 'bower install --force-latest --no-interactive' # install bower packages without asking about version conflict and install last version
after_script:
  - 'gulp test' # or other command for build, run tests, etc
